# Generated by Django 3.2.6 on 2021-08-27 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateField(default=datetime.date(2021, 8, 27)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
