# Generated by Django 3.2.6 on 2021-08-26 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date_joined',
            field=models.DateField(default=datetime.date(2021, 8, 26)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.TextField(default='00/00, address**'),
        ),
    ]
